### ISSUE TITLE
NPM install

### ISSUE THREAD

**Issue by ShuYuMo2003** [masnn/qqbot#1]
I think we also need to run `npm install` to install it.

**Comment by masnn** [comment]
Acturally we are using [yarn](https://yarnpkg.com) instead of npm.

**Comment by ShuYuMo2003** [comment]
> Acturally we are using [yarn](https://yarnpkg.com) instead of npm.

Oh sorry, I have NOT used `yarn`......

**Comment by masnn** [comment]
I'd agree that README.md might be unclear.
Feel free to open a pull request for it.
Thank you for using this program!
